parameters:

services:
    
    soap_listener:
        class: SoapBundle\Services\Listener\SoapListener
        public: true
        tags:
            - { name: kernel.event_listener, event: soap.call, method: onRequestSent }
        

    data_collector.soap:
        class: SoapBundle\Services\Collector\SoapCollector
        arguments: ['@soap_listener']
        tags:
            - { name: data_collector, template: "SoapBundle:Collector:soap.html.twig", id: "soap" }